[project]
name = "costslash"
version = "0.1.1"
description = "Instant AWS Cloud Cost & Waste Optimization Scanner"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.0.0",
    "pydantic>=2.0.0",
    "boto3>=1.28.0",
]

[project.scripts]
costslash = "costslash.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
